apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: data-park
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      initContainers:
      - name: init-jupyter
        image: busybox:1.28
        command: ['sh', '-c', 'cp -r /python/* /data/ && chmod -R 777 /data']
        volumeMounts:
        - name: notebook-volume
          mountPath: /data
        - name: python-code
          mountPath: /python
      containers:
      - name: jupyter-notebook
        image: jupyter/pyspark-notebook:python-3.11
        ports:
        - containerPort: 8888
          name: jupyter
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: SPARK_MASTER
          value: "local[*]"
        - name: SPARK_OPTS
          value: "--conf spark.driver.memory=1g --conf spark.executor.memory=1g"
        - name: GRANT_SUDO
          value: "yes"
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''", "--NotebookApp.password=''"]
        volumeMounts:
        - name: notebook-volume
          mountPath: /home/jovyan/work
        - name: jupyter-config
          mountPath: /home/jovyan/.ipython/profile_default/startup/00-spark-config.py
          subPath: jupyter_spark_config.py
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: notebook-volume
        persistentVolumeClaim:
          claimName: jupyter-pvc
      - name: jupyter-config
        configMap:
          name: jupyter-configmap
      - name: python-code
        hostPath:
          path: /home/gonzo/Desktop/Github/data_park/python
          type: Directory
