apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  namespace: data-park
  labels:
    app: jupyter-notebook
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    name: jupyter
  selector:
    app: jupyter-notebook
