apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: data-park
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      initContainers:
      - name: install-jdbc-driver
        image: curlimages/curl:7.88.1
        command: ['sh', '-c', 'curl -L https://jdbc.postgresql.org/download/postgresql-42.5.0.jar -O /drivers/postgresql-42.5.0.jar']
        volumeMounts:
        - name: jdbc-drivers
          mountPath: /drivers
      containers:
      - name: jupyter-notebook
        image: jupyter/pyspark-notebook:python-3.11
        ports:
        - containerPort: 8888
          name: jupyter
        env:
        - name: JUPYTER_BASE_URL
          value: "/jupyter"
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: SPARK_MASTER
          value: "spark://spark-master:7077"
        - name: SPARK_OPTS
          value: "--conf spark.driver.memory=1g --conf spark.executor.memory=1g --driver-class-path /opt/spark-jars/postgresql-42.5.0.jar --jars /opt/spark-jars/postgresql-42.5.0.jar"
        - name: GRANT_SUDO
          value: "yes"
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''", "--NotebookApp.password=''"]
        volumeMounts:
        - name: notebook-volume
          mountPath: /home/jovyan/work
        - name: jdbc-drivers
          mountPath: /opt/spark-jars
        - name: spark-init
          mountPath: /home/jovyan/work/init
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: notebook-volume
        persistentVolumeClaim:
          claimName: jupyter-pvc
      - name: jdbc-drivers
        emptyDir: {}
      - name: spark-init
        configMap:
          name: jupyter-spark-init
