apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: data-park
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      initContainers:
      - name: install-jdbc-driver
        image: curlimages/curl:7.88.1
        command: ['sh', '-c', 'curl -L https://jdbc.postgresql.org/download/postgresql-42.5.0.jar -O /drivers/postgresql-42.5.0.jar']
        volumeMounts:
        - name: jdbc-drivers
          mountPath: /drivers
      containers:
      - name: spark-master
        image: bitnami/spark:3.4.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7077
          name: master
        - containerPort: 8080
          name: ui
        env:
        - name: SPARK_MODE
          value: "master"
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        - name: SPARK_RPC_AUTHENTICATION_ENABLED
          value: "no"
        - name: SPARK_RPC_ENCRYPTION_ENABLED
          value: "no"
        - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
          value: "no"
        - name: SPARK_SSL_ENABLED
          value: "no"
        - name: SPARK_DRIVER_EXTRACLASSPATH
          value: "/opt/bitnami/spark/drivers/*"
        - name: SPARK_EXECUTOR_EXTRACLASSPATH
          value: "/opt/bitnami/spark/drivers/*"
        - name: SPARK_PUBLIC_DNS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: jdbc-drivers
          mountPath: /opt/bitnami/spark/drivers
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: jdbc-drivers
        emptyDir: {}
