apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: data-park
  labels:
    app: spark-master
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: ui
  - port: 7077
    targetPort: 7077
    name: master
  selector:
    app: spark-master
