apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-defaults
  namespace: data-park
data:
  spark-defaults.conf: |
    spark.master                     spark://spark-master:7077
    spark.eventLog.enabled           true
    spark.eventLog.dir               file:///spark-logs
    spark.history.fs.logDirectory    file:///spark-logs
    spark.sql.catalogImplementation  hive
    spark.sql.warehouse.dir          file:///opt/bitnami/spark/warehouse
    spark.driver.extraJavaOptions    -Dcom.amazonaws.services.s3.enableV4=true
    spark.executor.extraJavaOptions  -Dcom.amazonaws.services.s3.enableV4=true
    
    # Default spark-submit options
    spark.submit.deployMode          client
    spark.driver.memory              1g
    spark.executor.memory            1g
    spark.executor.instances         2
    spark.executor.cores             1
    
    # Connection to PostgreSQL
    spark.jars                       /opt/spark-jars/postgresql-42.6.0.jar
    
    # Streaming with Kafka
    spark.jars.packages              org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1
