apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: data-park
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      initContainers:
      - name: install-jdbc-driver
        image: curlimages/curl:7.88.1
        command: ['sh', '-c', 'curl -L https://jdbc.postgresql.org/download/postgresql-42.5.0.jar -O /drivers/postgresql-42.5.0.jar']
        volumeMounts:
        - name: jdbc-drivers
          mountPath: /drivers
      containers:
      - name: spark-worker
        image: bitnami/spark:3.4.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: ui
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8081"
        - name: SPARK_WORKER_MEMORY
          value: "1G"
        - name: SPARK_WORKER_CORES
          value: "1"
        - name: SPARK_RPC_AUTHENTICATION_ENABLED
          value: "no"
        - name: SPARK_RPC_ENCRYPTION_ENABLED
          value: "no"
        - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
          value: "no"
        - name: SPARK_SSL_ENABLED
          value: "no"
        - name: SPARK_EXECUTOR_EXTRACLASSPATH
          value: "/opt/bitnami/spark/drivers/*"
        - name: SPARK_PUBLIC_DNS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: jdbc-drivers
          mountPath: /opt/bitnami/spark/drivers
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: jdbc-drivers
        emptyDir: {}
