apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: data-park
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      containers:
      - name: spark-history-server
        image: bitnami/spark:3.4.1
        imagePullPolicy: IfNotPresent
        command:
        - /opt/bitnami/spark/bin/spark-class
        - org.apache.spark.deploy.history.HistoryServer
        ports:
        - containerPort: 18080
          name: history-ui
        env:
        - name: SPARK_HISTORY_OPTS
          value: "-Dspark.history.ui.port=18080 -Dspark.history.fs.logDirectory=/spark-logs -Dspark.history.retainedApplications=50"
        volumeMounts:
        - name: spark-logs
          mountPath: /spark-logs
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: spark-logs
        emptyDir: {}
