apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  namespace: data-park
  labels:
    app: spark-history-server
spec:
  ports:
  - port: 18080
    targetPort: 18080
    name: history-ui
  selector:
    app: spark-history-server
