apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  namespace: data-park
  labels:
    app: spark-history-server
spec:
  type: NodePort
  ports:
  - port: 18080
    targetPort: 18080
    nodePort: 30081
    name: ui
  selector:
    app: spark-history-server
