apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: data-park
  labels:
    app: spark-master
spec:
  ports:
  - port: 7077
    targetPort: 7077
    name: master
  - port: 8080
    targetPort: 8080
    name: ui
  selector:
    app: spark-master
