apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: data-park
  labels:
    app: airflow-webserver
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: web
  selector:
    app: airflow-webserver
