apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: data-park
data:
  airflow.cfg: |
    [core]
    executor = CeleryExecutor
    dags_folder = /opt/airflow/dags
    load_examples = False
    plugins_folder = /opt/airflow/plugins
    
    [database]
    sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    
    [webserver]
    web_server_port = 8080
    base_url = /
    navbar_color = #fff
    
    [scheduler]
    dag_dir_list_interval = 30
    
    [celery]
    broker_url = redis://redis:6379/0
    result_backend = db+postgresql://airflow:airflow@postgres:5432/airflow
    
    [api]
    auth_backends = airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session

  connections.yaml: |
    spark_default:
      conn_type: spark
      host: spark://spark-master:7077
      port: 7077
    
    postgres_default:
      conn_type: postgres
      host: postgres
      login: postgres
      password: postgrespass
      schema: postgres
      port: 5432
    
    postgres_datamart:
      conn_type: postgres
      host: postgres
      login: spark
      password: spark
      schema: datamart
      port: 5432
    
    kafka_default:
      conn_type: kafka
      host: kafka
      port: 9092
      extra: '{"bootstrap.servers": "kafka:9092"}'
