apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: data-park
  labels:
    app: airflow-webserver
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30082
    name: web
  selector:
    app: airflow-webserver
