apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: data-park
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: client
  clusterIP: None
  selector:
    app: kafka
