apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-init-topics
  namespace: data-park
data:
  create-topics.sh: |
    #!/bin/bash
    # Wait for Kafka to be ready
    sleep 30
    
    # Create topics
    kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic customer-events --partitions 3 --replication-factor 1
    kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic product-events --partitions 3 --replication-factor 1
    kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic order-events --partitions 3 --replication-factor 1
    kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic clickstream --partitions 3 --replication-factor 1
    
    # List topics
    kafka-topics --bootstrap-server kafka:9092 --list
